onEvent('recipes', event => {

    event.remove({id:'gateofbabylon:yoyo/wooden_yoyo'})
    event.remove({id:'gateofbabylon:yoyo/stone_yoyo'})
    event.remove({id:'gateofbabylon:yoyo/iron_yoyo'})
    event.remove({id:'gateofbabylon:yoyo/golden_yoyo'})
    event.remove({id:'gateofbabylon:yoyo/diamond_yoyo'})
    event.remove({id:'gateofbabylon:yoyo/netherite_yoyo'})

    event.remove({id:'gateofbabylon:dagger/wooden_dagger'})
    event.remove({id:'gateofbabylon:dagger/stone_dagger'})
    event.remove({id:'gateofbabylon:spear/wooden_spear'})
    event.remove({id:'gateofbabylon:spear/stone_spear'})
    event.remove({id:'gateofbabylon:broadsword/wooden_broadsword'})
    event.remove({id:'gateofbabylon:broadsword/stone_broadsword'})
    event.remove({id:'gateofbabylon:rapier/wooden_rapier'})
    event.remove({id:'gateofbabylon:rapier/stone_rapier'})
    event.remove({id:'gateofbabylon:haladie/wooden_haladie'})
    event.remove({id:'gateofbabylon:haladie/stone_haladie'})
    event.remove({id:'gateofbabylon:waraxe/wooden_waraxe'})
    event.remove({id:'gateofbabylon:waraxe/stone_waraxe'})
    event.remove({id:'gateofbabylon:katana/wooden_katana'})
    event.remove({id:'gateofbabylon:katana/stone_katana'})
    event.remove({id:'gateofbabylon:boomerang/wooden_boomerang'})
    event.remove({id:'gateofbabylon:boomerang/stone_boomerang'})
})