// \| \w+ \| \W+ \| ->',  
var normal_loot = [
    Item.of('minecraft:iron_ingot', 8),
    Item.of('minecraft:gold_ingot', 8),
    Item.of('minecraft:ender_pearl', 3),
    Item.of('minecraft:emerald', 5),
    Item.of('minecraft:experience_bottle', 8),
    '3x the_aether:zanite_gemstone',
    '3x mobz:hardenedmetal_ingot',
    '7x betternether:cincinnasite_ingot',
    '5x botania:manasteel_ingot',
    '3x kubejs:balloon_ingot',
    '3x kubejs:auritis_ingot',
    '3x kubejs:gravilite_ingot',
    'kubejs:red_packet',
    '3x mythicmetals:adamantite_ingot',
    '3x mythicmetals:aquarium_ingot',
    '3x mythicmetals:banglum_ingot',
    '3x mythicmetals:bronze_ingot',
    '3x mythicmetals:carmot_ingot',
    'mcda:upgrade_core',
    'mcda:upgrade_core_archer',
    'mcda:upgrade_core_depth',
    'mcda:upgrade_core_ember',
    'mcda:upgrade_core_fox',
    'mcda:upgrade_core_frost',
    'mcda:upgrade_core_glut',
    'mcda:upgrade_core_golden',
    'mcda:upgrade_core_highland',
    'mcda:upgrade_core_hive',
    'mcda:upgrade_core_magicked',
    'mcda:upgrade_core_metal',
    'mcda:upgrade_core_oceanic',
    'mcda:upgrade_core_shadows',
    'mcda:upgrade_core_soul',
    'mcda:upgrade_core_spider',
    'mcda:upgrade_core_verdant',
    'mcda:upgrade_core_void',
    'mcda:upgrade_core_wither',
    'mcda:upgrade_core_wolf'
]

var hard_loot = [
    Item.of('minecraft:diamond', 3),
    Item.of('minecraft:netherite_ingot', 2),
    Item.of('gobber2:gobber2_ingot', 2),
    Item.of('kubejs:upgrade_core_evolution', 1),
    '3x the_aether:ambrosium_shard',
    '3x the_aether:gravitite_gemstone',
    '3x mobz:boss_ingot',
    '5x betternether:nether_ruby',
    '3x botania:elementium_ingot',
    '3x kubejs:eden_ingot',
    '3x mythicmetals:celestium_ingot',
    '3x mythicmetals:hallowed_ingot',
    '3x mythicmetals:metallurgium_ingot',
    '3x mythicmetals:stormyx_ingot'
]

var impossible_loot = [
    Item.of('gobber2:gobber2_ingot_nether', 2),
    Item.of('gobber2:gobber2_ingot_end', 1),
    Item.of('dragonloot:dragon_scale', 1),
    Item.of('minecraft:enchanted_golden_apple', 1),
    'kubejs:jiushu_heart',
    '3x botania:terrasteel_ingot',
    '3x mythicmetals:unobtainium'
]

var jingying_loot = [
    Item.of('minecraft:enchanted_book').enchant('betterend:end_veil', 1),
    Item.of('minecraft:enchanted_book').enchant('betternether:obsidian_breaker', 1),
    Item.of('minecraft:enchanted_book').enchant('betternether:ruby_fire', 1),
    Item.of('minecraft:enchanted_book').enchant('doublejump:doublejump', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:auto_smelt', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:beheading', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:charged_bolt', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:consumer', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:double_swing', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:ender_mind', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:experience', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:glimmering', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:god_of_the_sea', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:god_of_thunder', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:homing', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:ice_aspect', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:nocturnal', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:paralysis', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:poison_aspect', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:pumpkin_head', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:pyromania', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:replenish', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:rise', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:shotgun', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:sniper', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:sugar_rush', 1),
    Item.of('minecraft:enchanted_book').enchant('fabricenchantments:tank', 1),
    Item.of('minecraft:enchanted_book').enchant('gateofbabylon:dragon_slash', 1),
    Item.of('minecraft:enchanted_book').enchant('gateofbabylon:flame_slash', 1),
    Item.of('minecraft:enchanted_book').enchant('gateofbabylon:lunging', 1),
    Item.of('minecraft:enchanted_book').enchant('gateofbabylon:quickdraw', 1),
    Item.of('minecraft:enchanted_book').enchant('gateofbabylon:smashing', 1),
    Item.of('minecraft:enchanted_book').enchant('gateofbabylon:thunder_slash', 1),
    Item.of('minecraft:enchanted_book').enchant('gateofbabylon:vampire_slash', 1),
    Item.of('minecraft:enchanted_book').enchant('gobber2:apotropaic', 1),
    Item.of('minecraft:enchanted_book').enchant('gobber2:blinders', 1),
    Item.of('minecraft:enchanted_book').enchant('gobber2:faster_obsidian', 1),
    Item.of('minecraft:enchanted_book').enchant('gobber2:fluid_master', 1),
    Item.of('minecraft:enchanted_book').enchant('gobber2:quickuse', 1),
    Item.of('minecraft:enchanted_book').enchant('gobber2:quietfeet', 1),
    Item.of('minecraft:enchanted_book').enchant('gobber2:rebuffing', 1),
    Item.of('minecraft:enchanted_book').enchant('gobber2:smithblade', 1),
    Item.of('minecraft:enchanted_book').enchant('gobber2:solidfooting', 1),
    Item.of('minecraft:enchanted_book').enchant('gobber2:summoner', 1),
    Item.of('minecraft:enchanted_book').enchant('gobber2:untouchable', 1),
    Item.of('minecraft:enchanted_book').enchant('imperishableitems:imperishable', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:bunnys_hop', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:charmed', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:decay', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:forging_touch', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:last_stand', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:magnetic', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:reaping_rod', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:recklessness', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:retreat', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:swine_bane', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:thunder', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:tough_luck', 1),
    Item.of('minecraft:enchanted_book').enchant('incantationem:venomous', 1),
    Item.of('minecraft:enchanted_book').enchant('magiccombatwands:concentration', 1),
    Item.of('minecraft:enchanted_book').enchant('magiccombatwands:magic_protection', 1),
    Item.of('minecraft:enchanted_book').enchant('magiccombatwands:magic_wind', 1),
    Item.of('minecraft:enchanted_book').enchant('magiccombatwands:skillful', 1),
    Item.of('minecraft:enchanted_book').enchant('magiccombatwands:thrifty', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:bag_of_souls', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:burning', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:chilling', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:cowardice', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:death_barter', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:deflect', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:fire_focus', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:fire_trail', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:food_reserves', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:frenzied', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:heal_allies', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:lucky_explorer', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:poison_focus', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:potion_barrier', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:reckless', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:recycler', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:snowball', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:surprise_gift', 1),
    Item.of('minecraft:enchanted_book').enchant('mcda:swiftfooted', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdar:beast_boss', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdar:beast_burst', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdar:beast_surge', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdar:cooldown', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:ambush', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:anima_conduit', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:bonus_shot', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:chain_reaction', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:chains', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:charge', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:cobweb_shot', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:committed', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:critical_hit', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:dipping_poison', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:echo', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:enigma_resonator', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:exploding', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:freezing', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:fuse_shot', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:gravity', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:growing', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:guarding_strike', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:illagers_bane', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:jungle_poison', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:leeching', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:levitation_shot', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:phantoms_mark', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:poison_cloud', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:prospector', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:radiance', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:rampaging', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:refreshment', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:replenish', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:ricochet', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:rushdown', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:shockwave', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:smiting', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:soul_devourer', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:soul_siphon', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:stunning', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:swirling', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:tempo_theft', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:thundering', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:void_shot', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:void_strike', 1),
    Item.of('minecraft:enchanted_book').enchant('mcdw:weakening', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:aqua_affinity', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:bane_of_arthropods', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:binding_curse', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:blast_protection', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:channeling', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:depth_strider', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:efficiency', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:feather_falling', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:fire_aspect', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:fire_protection', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:flame', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:fortune', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:frost_walker', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:impaling', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:infinity', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:knockback', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:looting', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:loyalty', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:luck_of_the_sea', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:lure', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:mending', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:multishot', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:piercing', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:power', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:projectile_protection', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:protection', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:punch', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:quick_charge', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:respiration', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:riptide', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:sharpness', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:silk_touch', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:smite', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:soul_speed', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:sweeping', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:thorns', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:unbreaking', 1),
    Item.of('minecraft:enchanted_book').enchant('minecraft:vanishing_curse', 1),
    Item.of('minecraft:enchanted_book').enchant('things:retribution', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:auto_fish', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:broken_dawn', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:climber', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:diffusion', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:down_armor', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:down_damage', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:elasticity', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:halo_height_advantage', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:hit_rate_up', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:increment_attack_damage', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:king_kong_legs', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:librarian', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:magic_immune', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:more_loot', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:night_break', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:quick_shot', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:rebirth', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:regicide', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:smart', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:suck_blood', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:thin', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:timor', 1),
    Item.of('minecraft:enchanted_book').enchant('x_enchant:weakness', 1),
    Item.of('minecraft:enchanted_book').enchant('yigd:death_sight', 1),
    Item.of('minecraft:enchanted_book').enchant('yigd:soulbound', 1),
    'mcdw:axe_anchor',
    'mcdw:axe_axe',
    'mcdw:axe_cursed',
    'mcdw:axe_double',
    'mcdw:axe_encrusted_anchor',
    'mcdw:axe_firebrand',
    'mcdw:axe_highland',
    'mcdw:axe_whirlwind',
    'mcdw:bow_ancient_bow',
    'mcdw:bow_bonebow',
    'mcdw:bow_bubble_bow',
    'mcdw:bow_bubble_burster',
    'mcdw:bow_burst_gale_bow',
    'mcdw:bow_call_of_the_void',
    'mcdw:bow_echo_of_the_valley',
    'mcdw:bow_elite_power_bow',
    'mcdw:bow_green_menace',
    'mcdw:bow_guardian_bow',
    'mcdw:bow_haunted_bow',
    'mcdw:bow_hunters_promise',
    'mcdw:bow_hunting_bow',
    'mcdw:bow_longbow',
    'mcdw:bow_lost_souls',
    'mcdw:bow_love_spell_bow',
    'mcdw:bow_masters_bow',
    'mcdw:bow_mechanical_shortbow',
    'mcdw:bow_nocturnal_bow',
    'mcdw:bow_phantom_bow',
    'mcdw:bow_pink_scoundrel',
    'mcdw:bow_power_bow',
    'mcdw:bow_purple_storm',
    'mcdw:bow_red_snake',
    'mcdw:bow_sabrewing',
    'mcdw:bow_shivering_bow',
    'mcdw:bow_shortbow',
    'mcdw:bow_snow_bow',
    'mcdw:bow_soul_bow',
    'mcdw:bow_trickbow',
    'mcdw:bow_twin_bow',
    'mcdw:bow_twisting_vine_bow',
    'mcdw:bow_void_bow',
    'mcdw:bow_web_bow',
    'mcdw:bow_weeping_vine_bow',
    'mcdw:bow_wind_bow',
    'mcdw:bow_winters_touch',
    'mcdw:crossbow_auto_crossbow',
    'mcdw:crossbow_azure_seeker',
    'mcdw:crossbow_baby_crossbow',
    'mcdw:crossbow_burst_crossbow',
    'mcdw:crossbow_butterfly_crossbow',
    'mcdw:crossbow_cog_crossbow',
    'mcdw:crossbow_corrupted_crossbow',
    'mcdw:crossbow_doom_crossbow',
    'mcdw:crossbow_dual_crossbow',
    'mcdw:crossbow_exploding_crossbow',
    'mcdw:crossbow_feral_soul_crossbow',
    'mcdw:crossbow_firebolt_thrower',
    'mcdw:crossbow_harp_crossbow',
    'mcdw:crossbow_harpoon_crossbow',
    'mcdw:crossbow_heavy_crossbow',
    'mcdw:crossbow_imploding_crossbow',
    'mcdw:crossbow_lightning_harp_crossbow',
    'mcdw:crossbow_nautical_crossbow',
    'mcdw:crossbow_pride_of_the_piglins',
    'mcdw:crossbow_rapid_crossbow',
    'mcdw:crossbow_scatter_crossbow',
    'mcdw:crossbow_shadow_crossbow',
    'mcdw:crossbow_slayer_crossbow',
    'mcdw:crossbow_soul_crossbow',
    'mcdw:crossbow_soul_hunter_crossbow',
    'mcdw:crossbow_spellbound_crossbow',
    'mcdw:crossbow_the_slicer',
    'mcdw:crossbow_veiled_crossbow',
    'mcdw:crossbow_voidcaller_crossbow',
    'mcdw:dagger_backstabber',
    'mcdw:dagger_chill_gale_knife',
    'mcdw:dagger_dagger',
    'mcdw:dagger_eternal_knife',
    'mcdw:dagger_fangs_of_frost',
    'mcdw:dagger_moon',
    'mcdw:dagger_resolute_tempest_knife',
    'mcdw:dagger_shear_dagger',
    'mcdw:dagger_soul_knife',
    'mcdw:dagger_swift_striker',
    'mcdw:dagger_tempest_knife',
    'mcdw:dagger_the_beginning',
    'mcdw:dagger_the_end',
    'mcdw:dagger_void_touched_blade',
    'mcdw:gauntlet_gauntlet',
    'mcdw:gauntlet_maulers',
    'mcdw:gauntlet_soul_fists',
    'mcdw:hammer_bone_cudgel',
    'mcdw:hammer_boneclub',
    'mcdw:hammer_flail',
    'mcdw:hammer_gravity',
    'mcdw:hammer_great_hammer',
    'mcdw:hammer_mace',
    'mcdw:hammer_stormlander',
    'mcdw:hammer_suns_grace',
    'mcdw:item_bee_stinger',
    'mcdw:pick_diamond_pickaxe_var',
    'mcdw:pick_hailing_pinnacle',
    'mcdw:pick_howling_pick',
    'mcdw:pick_mountaineer_pick',
    'mcdw:shield_royal_guard',
    'mcdw:shield_vanguard',
    'mcdw:sickle_frost_scythe',
    'mcdw:sickle_jailors_scythe',
    'mcdw:sickle_last_laugh_gold',
    'mcdw:sickle_last_laugh_silver',
    'mcdw:sickle_nightmares_bite',
    'mcdw:sickle_sickle',
    'mcdw:sickle_skull_scythe',
    'mcdw:sickle_soul_scythe',
    'mcdw:spear_cackling_broom',
    'mcdw:spear_fortune',
    'mcdw:spear_glaive',
    'mcdw:spear_grave_bane',
    'mcdw:spear_spear',
    'mcdw:spear_venom_glaive',
    'mcdw:spear_whispering_spear',
    'mcdw:staff_battlestaff',
    'mcdw:staff_battlestaff_of_terror',
    'mcdw:staff_growing_staff',
    'mcdw:sword_beestinger',
    'mcdw:sword_broadsword',
    'mcdw:sword_broken_sawblade',
    'mcdw:sword_claymore',
    'mcdw:sword_coral_blade',
    'mcdw:sword_cutlass',
    'mcdw:sword_dancers_sword',
    'mcdw:sword_dark_katana',
    'mcdw:sword_diamond_sword_var',
    'mcdw:sword_freezing_foil',
    'mcdw:sword_frost_slayer',
    'mcdw:sword_great_axeblade',
    'mcdw:sword_hawkbrand',
    'mcdw:sword_heartstealer',
    'mcdw:sword_iron_sword_var',
    'mcdw:sword_katana',
    'mcdw:sword_masters_katana',
    'mcdw:sword_mechanized_sawblade',
    'mcdw:sword_nameless_blade',
    'mcdw:sword_obsidian_claymore',
    'mcdw:sword_rapier',
    'mcdw:sword_sinister',
    'mcdw:sword_sponge_striker',
    'mcdw:sword_the_starless_night',
    'mcdw:sword_truthseeker',
    'mcdw:whip_vine_whip',
    'mcdw:whip_whip',
    'mcdar:blast_fungus',
    'mcdar:boots_of_swiftness',
    'mcdar:buzzy_nest',
    'mcdar:corrupted_seeds',
    'mcdar:death_cap_mushroom',
    'mcdar:enchanted_grass',
    'mcdar:enchanters_tome',
    'mcdar:flaming_quiver',
    'mcdar:ghost_cloak',
    'mcdar:golem_kit',
    'mcdar:gong_of_weakening',
    'mcdar:harpoon_quiver',
    'mcdar:harvester',
    'mcdar:iron_hide_amulet',
    'mcdar:light_feather',
    'mcdar:lightning_rod',
    'mcdar:powershaker',
    'mcdar:satchel_of_elements',
    'mcdar:shock_powder',
    'mcdar:soul_healer',
    'mcdar:tasty_bone',
    'mcdar:thundering_quiver',
    'mcdar:torment_quiver',
    'mcdar:totem_of_regeneration',
    'mcdar:totem_of_shielding',
    'mcdar:totem_of_soul_protection',
    'mcdar:updraft_tome',
    'mcdar:wind_horn',
    'mcdar:wonderful_wheat'
]

