// priority: 0


onEvent('rei.hide.items', event => {
	event.hide('minecraft:stone_sword')
	event.hide('minecraft:stone_shovel')
	event.hide('minecraft:stone_pickaxe')
	event.hide('minecraft:stone_axe')
	event.hide('minecraft:stone_hoe')

	event.hide('minecraft:wooden_sword')
	event.hide('minecraft:wooden_shovel')
	event.hide('minecraft:wooden_pickaxe')
	event.hide('minecraft:wooden_axe')
	event.hide('minecraft:wooden_hoe')
	event.hide('treeaxe:wooden_treeaxe')

	event.hide('gobber2:gobber2_ring_dismissal')
	event.hide('gobber2:gobber2_ring_explorer')
	event.hide('gobber2:gobber2_ring_airwalking')
	event.hide('gobber2:gobber2_ring_strength')
	event.hide('gobber2:gobber2_ring_swiftness')
	event.hide('gobber2:gobber2_ring_above')
	event.hide('gobber2:gobber2_medallion_healing3')
	event.hide('gobber2:gobber2_medallion_healing2')
	event.hide('gobber2:gobber2_special_item')
	event.hide('gobber2:gobber2_medallion_hero')
	event.hide('gobber2:gobber2_ring_stealth')
	event.hide('gobber2:gobber2_medallion_healing')

	event.hide('gateofbabylon:wooden_haladie')
	event.hide('gateofbabylon:stone_haladie')
	event.hide('gateofbabylon:wooden_waraxe')
	event.hide('gateofbabylon:stone_waraxe')
	event.hide('gateofbabylon:wooden_katana')
	event.hide('gateofbabylon:stone_katana')
	event.hide('gateofbabylon:wooden_boomerang')
	event.hide('gateofbabylon:stone_boomerang')
	event.hide('gateofbabylon:wooden_rapier')
	event.hide('gateofbabylon:stone_rapier')
	event.hide('gateofbabylon:wooden_broadsword')
	event.hide('gateofbabylon:stone_broadsword')
	event.hide('gateofbabylon:wooden_spear')
	event.hide('gateofbabylon:wooden_spear')
	event.hide('gateofbabylon:wooden_dagger')
	event.hide('gateofbabylon:stone_dagger')
	event.hide('gateofbabylon:wooden_yoyo')
	event.hide('gateofbabylon:stone_yoyo')
	event.hide('gateofbabylon:iron_yoyo')
	event.hide('gateofbabylon:golden_yoyo')
	event.hide('gateofbabylon:diamond_yoyo')
	event.hide('gateofbabylon:netherite_yoyo')
})